-- Disposable local rollback-only fixtures; never hosted or provider-connected.
\ir fixtures/curiosity-source.sql
truncate pg_temp.qa_results;
create function pg_temp.ai_admit(hash text) returns jsonb language sql as $$ select public.admit_ai_reasoning(current_setting('test.g_pa')::uuid,current_setting('test.g_import')::uuid,'PLANNING',current_setting('test.qa_first')::uuid,'gpt-4.1-mini',hash); $$;
set local role authenticated;
select set_config('ai.ticket',pg_temp.ai_admit(repeat('a',64))::text,true);
select pg_temp.assert_true((select state='RESERVED' and reserved_micro_usd=11200 and reserved_input_tokens=12000 and reserved_output_tokens=4000 and usage_estimated and result_id is null from public.ai_reasoning_requests),'fixed worst-case reservation and no result');
select pg_temp.expect_error('select pg_temp.ai_admit(repeat(''a'',64))','23505','duplicate submission blocked');
select pg_temp.expect_error('select pg_temp.ai_admit(repeat(''b'',64))','54000','project concurrent admission blocked');
select pg_temp.expect_error('select nonce from public.ai_reasoning_requests','42501','nonce excluded from ordinary reads');
select pg_temp.expect_error('update public.ai_reasoning_requests set state=''COMPLETED''','42501','direct ledger writes blocked');
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket'')::jsonb->>''id'')::uuid,gen_random_uuid(),''FAILED'',''{}'',null)','42501','forged nonce blocked');
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket'')::jsonb->>''id'')::uuid,(current_setting(''ai.ticket'')::jsonb->>''nonce'')::uuid,''FAILED'',''{}'',''{"approved":true}'')','23514','failed request cannot persist output');
select public.complete_ai_reasoning((current_setting('ai.ticket')::jsonb->>'id')::uuid,(current_setting('ai.ticket')::jsonb->>'nonce')::uuid,'FAILED','{"inputTokens":null,"outputTokens":null,"responseId":null,"errorCode":"NETWORK"}',null);
select pg_temp.assert_true((select state='FAILED' and usage_estimated and input_tokens is null and result_id is null and reserved_micro_usd=11200 from public.ai_reasoning_requests),'unknown usage retains estimate and cannot create proposal');
select pg_temp.expect_error('select pg_temp.ai_admit(repeat(''b'',64))','54000','failure cannot refund rolling admission');
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket'')::jsonb->>''id'')::uuid,(current_setting(''ai.ticket'')::jsonb->>''nonce'')::uuid,''FAILED'',''{}'',null)','40001','settled receipt cannot be overwritten');
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000002',true);
select pg_temp.assert_true((select count(*)=0 from public.ai_reasoning_requests),'cross-tenant usage hidden');
select pg_temp.expect_error('select pg_temp.ai_admit(repeat(''c'',64))','42501','cross-tenant admission blocked');
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket'')::jsonb->>''id'')::uuid,(current_setting(''ai.ticket'')::jsonb->>''nonce'')::uuid,''FAILED'',''{}'',null)','42501','cross-tenant settlement blocked');
reset role;
update public.ai_reasoning_requests set created_at=clock_timestamp()-interval '121 seconds';
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select pg_temp.expect_error('select public.admit_ai_reasoning(current_setting(''test.g_pa'')::uuid,current_setting(''test.g_import2'')::uuid,''PLANNING'',current_setting(''test.qa_first'')::uuid,''gpt-4.1-mini'',repeat(''c'',64))','23514','cross-project source substitution blocked');
select pg_temp.expect_error('select public.admit_ai_reasoning(current_setting(''test.g_pa'')::uuid,current_setting(''test.g_import'')::uuid,''PLANNING'',current_setting(''test.qa_first'')::uuid,''unpriced-model'',repeat(''c'',64))','23514','unpriced model blocked');
select set_config('ai.ticket2',pg_temp.ai_admit(repeat('b',64))::text,true);
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket2'')::jsonb->>''id'')::uuid,(current_setting(''ai.ticket2'')::jsonb->>''nonce'')::uuid,''COMPLETED'',''{}'',''{"workspaceId":"forged"}'')','23514','invalid proposal rejected atomically');
select pg_temp.assert_true((select state='RESERVED' from public.ai_reasoning_requests where id=(current_setting('ai.ticket2')::jsonb->>'id')::uuid),'failed atomic completion retains reservation');
select pg_temp.expect_error('select public.complete_ai_reasoning((current_setting(''ai.ticket2'')::jsonb->>''id'')::uuid,(current_setting(''ai.ticket2'')::jsonb->>''nonce'')::uuid,''FAILED'',''{"inputTokens":1.5,"outputTokens":1}'',null)','23514','fractional usage cannot be rounded into trusted counts');
select public.complete_ai_reasoning((current_setting('ai.ticket2')::jsonb->>'id')::uuid,(current_setting('ai.ticket2')::jsonb->>'nonce')::uuid,'UNCERTAIN','{"inputTokens":null,"outputTokens":null,"responseId":null,"errorCode":"USAGE_UNCERTAIN"}',null);
select pg_temp.assert_true((select state='UNCERTAIN' and usage_estimated from public.ai_reasoning_requests where id=(current_setting('ai.ticket2')::jsonb->>'id')::uuid),'accounting uncertainty explicit');
reset role;
update public.ai_reasoning_requests set created_at=clock_timestamp()-interval '121 seconds';
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.run')::uuid);
select set_config('ai.inv',public.derive_investigation(current_setting('ev.run')::uuid)::text,true);
select set_config('ai.inv_ticket',public.admit_ai_reasoning(current_setting('test.g_pa')::uuid,current_setting('test.g_import')::uuid,'INVESTIGATION',current_setting('ai.inv')::uuid,'gpt-4.1-mini',repeat('c',64))::text,true);
select set_config('ai.proposal',public.complete_ai_reasoning((current_setting('ai.inv_ticket')::jsonb->>'id')::uuid,(current_setting('ai.inv_ticket')::jsonb->>'nonce')::uuid,'COMPLETED','{"inputTokens":123,"outputTokens":45,"responseId":"resp_fixture","errorCode":null}',jsonb_build_object('caseId',current_setting('exec.case'),'hypothesis','Repeat the selected case to assess its declared assertions.','rationale','Review assertion repeatability; cause remains unknown.','confidence','LOW','evidenceItemIds',(select jsonb_build_array(id) from public.evidence_items where package_id=(select source_package_id from public.investigations where id=current_setting('ai.inv')::uuid) order by id limit 1),'dependencyId',null,'bindings','[]'::jsonb))::text,true);
select pg_temp.assert_true((select state='COMPLETED' and not usage_estimated and input_tokens=123 and result_id=current_setting('ai.proposal')::uuid from public.ai_reasoning_requests where id=(current_setting('ai.inv_ticket')::jsonb->>'id')::uuid),'usage and proposal persist atomically');
select pg_temp.assert_true((select status='PROPOSED' and approved_by is null and run_id is null from public.investigation_proposals where id=current_setting('ai.proposal')::uuid),'AI requires human approval and creates no run');
select pg_temp.expect_error('select public.materialize_investigation_proposal(current_setting(''ai.proposal'')::uuid,(select fingerprint from public.investigation_proposals where id=current_setting(''ai.proposal'')::uuid))','23514','AI cannot bypass execution approval');
reset role;
update public.ai_reasoning_requests set created_at=clock_timestamp()-interval '121 seconds';
set local role authenticated;
select set_config('ai.plan_ticket',pg_temp.ai_admit(repeat('e',64))::text,true);
select set_config('ai.plan',public.complete_ai_reasoning((current_setting('ai.plan_ticket')::jsonb->>'id')::uuid,(current_setting('ai.plan_ticket')::jsonb->>'nonce')::uuid,'COMPLETED','{"inputTokens":100,"outputTokens":20}',jsonb_set(jsonb_set(pg_temp.plan_payload(),'{requirements,0,status}','"APPROVED"'),'{requirements,0,reviewId}',to_jsonb(current_setting('test.qa_approval')))||jsonb_build_object('aiStatus','SUCCEEDED','aiMetadata',jsonb_build_object('provider','openai','model','gpt-4.1-mini','promptVersion','planning-1'),'items',jsonb_build_array(pg_temp.test_definition()||jsonb_build_object('origin','AI_PROPOSED','derivationType','AI_INFERENCE','confidence','SUPPORTED'))))::text,true);
select pg_temp.assert_true((select status='DRAFT' and ai_status='SUCCEEDED' from public.test_plans where id=current_setting('ai.plan')::uuid),'AI planning persists draft with receipt');
select pg_temp.assert_true((select bool_and(origin='AI_PROPOSED' and definition->'executable'='false'::jsonb) from public.test_items where plan_id=current_setting('ai.plan')::uuid),'AI planning remains non-executable');
reset role;
update public.ai_reasoning_requests set created_at=clock_timestamp()-interval '121 seconds';
insert into public.ai_reasoning_requests(workspace_id,project_id,api_import_id,created_by,workflow,anchor_id,model,context_hash,created_at)
 select current_setting('test.g_wa')::uuid,current_setting('test.g_pa')::uuid,current_setting('test.g_import')::uuid,'14000000-0000-0000-0000-000000000001','PLANNING',current_setting('test.qa_first')::uuid,'gpt-4.1-mini',encode(sha256(convert_to(n::text,'UTF8')),'hex'),clock_timestamp()-interval '121 seconds' from generate_series(1,6) n;
set local role authenticated;
select pg_temp.expect_error('select pg_temp.ai_admit(repeat(''d'',64))','54000','daily project and actor limits cannot be refunded');
reset role;
select pg_temp.assert_true((select relrowsecurity from pg_class where oid='public.ai_reasoning_requests'::regclass),'ledger RLS enabled');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.admit_ai_reasoning(uuid,uuid,text,uuid,text,text)','EXECUTE') and not has_function_privilege('anon','public.complete_ai_reasoning(uuid,uuid,text,jsonb,jsonb)','EXECUTE'),'runner and anon reasoning authority unchanged');
select pg_temp.assert_true(not has_table_privilege('service_role','public.ai_reasoning_requests','SELECT,INSERT,UPDATE,DELETE'),'service role has no ledger access');
select public.validate_execution_runner_role();
select count(*) as ai_reasoning_assertions from pg_temp.qa_results;
rollback;
