-- Disposable local fixtures: actual SQL RPCs, no HTTP or hosted writes.
\ir fixtures/execution-source.sql
truncate pg_temp.qa_results;
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select set_config('exec.case',(select id::text from public.test_items where plan_id=current_setting('test.eligible')::uuid and kind='CASE'),true);
select set_config('exec.parent',(select scenario_id::text from public.test_items where id=current_setting('exec.case')::uuid),true);
select public.review_test_item(current_setting('exec.parent')::uuid,null,'APPROVE','',null,null,null);
select public.review_test_item(current_setting('exec.case')::uuid,null,'APPROVE','',null,null,null);
select set_config('exec.environment',(select id::text from public.environments where project_id=current_setting('test.g_pa')::uuid and type='DEVELOPMENT'),true);
select set_config('exec.config',public.configure_execution_environment(current_setting('exec.environment')::uuid,'https://api.example.test/',443,true)::text,true);
reset role;
create function pg_temp.evidence_run(outcome text,failure text default null,expected_status integer default 200) returns uuid language plpgsql as $$
declare run_id uuid;job jsonb;payload jsonb;status_code integer:=case when outcome='FAILED' then 500 else 200 end;
begin
 execute 'set local role authenticated';perform set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
 run_id:=public.request_test_execution(current_setting('exec.case')::uuid,current_setting('exec.environment')::uuid);
 execute 'set local role testpilot_runner';job:=public.claim_test_execution();
 perform public.record_execution_safety(run_id,(job->'run'->>'claim_token')::uuid,'ALLOW','[]','{}',jsonb_set('{"method":"GET","url":"https://api.example.test/","headers":{},"body":null,"assertions":[{"kind":"STATUS_IN_DECLARED_SET","expected":[200],"pointer":"#/info"}],"operationPointer":"#/info"}', '{assertions,0,expected}',jsonb_build_array(expected_status)),repeat('c',64));
 job:=public.claim_test_execution();
 perform public.authorize_execution_send(run_id,(job->'run'->>'claim_token')::uuid,repeat('c',64),(job->'run'->>'config_id')::uuid,'1.0.0');
 payload:=jsonb_build_object('outcome',outcome,'sent',outcome in ('FAILED','PASSED'),'failure',failure,'response',case when outcome in ('FAILED','PASSED') then jsonb_build_object('status',status_code,'headers',jsonb_build_object('set-cookie','[REDACTED]','content-type','application/json'),'body','{"field_0":"[REDACTED]"}','bodyHandling','JSON','contentType','application/json','bytes',26,'durationMs',10,'observedAt','2026-10-07T00:00:00.000Z') end,'assertions',case when outcome in ('FAILED','PASSED') then jsonb_build_array(jsonb_build_object('kind','STATUS_IN_DECLARED_SET','expected',jsonb_build_array(expected_status),'pointer','#/info','status',case when outcome='FAILED' then 'FAIL' else 'PASS' end,'actual',status_code::text,'reason','Compared observed response with declared assertion.')) else '[]'::jsonb end);
 perform public.finish_test_execution(run_id,(job->'run'->>'claim_token')::uuid,payload);
 execute 'reset role';return run_id;
end;$$;
select set_config('ev.run',pg_temp.evidence_run('FAILED')::text,true);
set local role authenticated;
select set_config('ev.package',public.derive_execution_evidence(current_setting('ev.run')::uuid)::text,true);
select set_config('ev.finding',(select id::text from public.findings where first_package_id=current_setting('ev.package')::uuid),true);
select pg_temp.assert_true((select count(*)=1 from public.evidence_packages),'one persisted-result package');
select pg_temp.assert_true((select count(*)=5 from public.evidence_items),'typed references without duplicate payload');
select pg_temp.assert_true((select status='CANDIDATE' and severity='MEDIUM' and confidence='HIGH' from public.findings),'assertion failure candidate not confirmed');
select pg_temp.assert_true(public.derive_execution_evidence(current_setting('ev.run')::uuid)=current_setting('ev.package')::uuid,'idempotent package identity');
select pg_temp.assert_true((select count(*)=1 from public.finding_occurrences),'no duplicate occurrence');
select pg_temp.assert_true((select count(*)=2 from public.finding_audit_events),'no duplicate audit');
select pg_temp.assert_true((select length(fingerprint)=64 from public.evidence_packages),'SHA256 integrity');
select pg_temp.assert_true((select result->'response'->>'body'='{"field_0":"[REDACTED]"}' from public.execution_results where run_id=current_setting('ev.run')::uuid),'redaction preserved');
select pg_temp.assert_true((select count(*)>0 from public.test_item_qa_links where item_id=current_setting('exec.case')::uuid),'requirement risk links preserved');
select pg_temp.expect_error('update public.evidence_packages set fingerprint=repeat(''0'',64)','42501','immutable evidence');
select pg_temp.expect_error('delete from public.evidence_items','42501','immutable items');
select pg_temp.expect_error('insert into public.evidence_packages(workspace_id) values(current_setting(''test.g_wa'')::uuid)','42501','browser evidence forgery denied');
select pg_temp.expect_error('update public.findings set status=''CONFIRMED''','42501','direct authoritative state denied');
select pg_temp.expect_error('insert into public.finding_occurrences(finding_id) values(current_setting(''ev.finding'')::uuid)','42501','forged occurrence denied');
select pg_temp.expect_error('insert into public.finding_reviews(finding_id) values(current_setting(''ev.finding'')::uuid)','42501','forged review denied');
select pg_temp.expect_error('delete from public.finding_audit_events','42501','audit deletion denied');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,1,''CONFIRM'',''HIGH'','''')','40001','stale review rejected');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,0,''INVALID'',''HIGH'','''')','23514','invalid decision');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,0,''CONFIRM'',''INVALID'','''')','23514','invalid severity');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,0,''CONFIRM'',''HIGH'',repeat(''x'',1001))','23514','oversized note');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,0,''CONFIRM'',''HIGH'',''token=fixture-secret'')','23514','credential-like note');

do $$ declare note text;reviews_before bigint;audits_before bigint;state_before jsonb;
begin
 foreach note in array array['Authorization: Bearer synthetic_fixture_value','bearer synthetic_fixture_value','https://fixture:synthetic_fixture_value@example.invalid','postgresql://fixture:synthetic_fixture_value@localhost/fixture','api_key=synthetic_fixture_value','access_token: synthetic_fixture_value','cookie=synthetic_fixture_value','sb_secret_synthetic_fixture_value','-----BEGIN PRIVATE KEY-----'] loop
 select count(*) into reviews_before from public.finding_reviews;
 select count(*) into audits_before from public.finding_audit_events;
 select jsonb_build_array(status,severity,revision) into state_before from public.findings where id=current_setting('ev.finding')::uuid;
 perform pg_temp.expect_error(format('select public.review_finding(%L::uuid,0,''CONFIRM'',''CRITICAL'',%L)',current_setting('ev.finding'),note),'23514','recognized credential rejected: '||array_position(array['Authorization: Bearer synthetic_fixture_value','bearer synthetic_fixture_value','https://fixture:synthetic_fixture_value@example.invalid','postgresql://fixture:synthetic_fixture_value@localhost/fixture','api_key=synthetic_fixture_value','access_token: synthetic_fixture_value','cookie=synthetic_fixture_value','sb_secret_synthetic_fixture_value','-----BEGIN PRIVATE KEY-----'],note));
 perform pg_temp.assert_true((select count(*)=reviews_before from public.finding_reviews) and (select count(*)=audits_before from public.finding_audit_events) and (select jsonb_build_array(status,severity,revision)=state_before from public.findings where id=current_setting('ev.finding')::uuid),'rejected credential leaves no partial review/state/audit: '||md5(note));
 end loop;
end;$$;
select pg_temp.expect_error('select public.derive_execution_evidence(gen_random_uuid())','42501','nonexistent execution');
reset role;
select set_config('ev.second',pg_temp.evidence_run('FAILED')::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.second')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.findings),'stable logical finding');
select pg_temp.assert_true((select occurrence_count=2 from public.findings),'repeat occurrence count');
select pg_temp.assert_true((select count(*)=2 from public.evidence_packages),'distinct per-run evidence');
select public.review_finding(current_setting('ev.finding')::uuid,0,'CONFIRM','HIGH','Declared status mismatch reviewed.');
select pg_temp.assert_true((select status='CONFIRMED' and severity='HIGH' and revision=1 from public.findings),'human confirmation severity');
select pg_temp.assert_true((select count(*)=1 and bool_and(actor_id=auth.uid() and previous_status='CANDIDATE' and new_status='CONFIRMED') from public.finding_reviews),'attributed append-only history');
select pg_temp.assert_true((select count(*)=1 from public.finding_audit_events where event='FINDING_SEVERITY_CHANGED'),'severity audited');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,1,''DISMISS'',''LOW'','''')','40001','review cannot overwrite decision');
reset role;
select set_config('ev.third',pg_temp.evidence_run('FAILED')::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.third')::uuid);
select pg_temp.assert_true((select status='CONFIRMED' and severity='HIGH' and revision=1 and occurrence_count=3 from public.findings),'repeat preserves human authority');
reset role;
select set_config('ev.pass',pg_temp.evidence_run('PASSED')::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.pass')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.findings),'success no finding');
reset role;
select set_config('ev.timeout',pg_temp.evidence_run('ERROR','TIMEOUT')::text,true);
select set_config('ev.transport',pg_temp.evidence_run('ERROR','TRANSPORT_FAILURE')::text,true);
select set_config('ev.cancel',pg_temp.evidence_run('CANCELLED','CANCELLED')::text,true);
select set_config('ev.block',pg_temp.evidence_run('BLOCKED','SAFETY_BLOCKED')::text,true);
select set_config('ev.stale',pg_temp.evidence_run('BLOCKED','BLOCK_AUTHORIZATION_STALE')::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.timeout')::uuid);
select public.derive_execution_evidence(current_setting('ev.transport')::uuid);
select public.derive_execution_evidence(current_setting('ev.cancel')::uuid);
select public.derive_execution_evidence(current_setting('ev.block')::uuid);
select public.derive_execution_evidence(current_setting('ev.stale')::uuid);
select pg_temp.assert_true((select count(*)=3 from public.findings),'cancel safety stale excluded from defects');
select pg_temp.assert_true((select severity='INFO' and confidence='MEDIUM' from public.findings where rule='EXECUTION_TIMEOUT'),'timeout is infrastructure observation');
select pg_temp.assert_true((select severity='INFO' and confidence='LOW' from public.findings where rule='TRANSPORT_FAILURE'),'transport confidence separate');
select public.review_finding((select id from public.findings where rule='EXECUTION_TIMEOUT'),0,'DISMISS','INFO','Infrastructure observation dismissed.');
select pg_temp.assert_true((select status='DISMISSED' from public.findings where rule='EXECUTION_TIMEOUT'),'human dismissal');
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000003',true);
select pg_temp.assert_true((select count(*)=0 from public.findings),'cross-workspace findings hidden');
select pg_temp.assert_true((select count(*)=0 from public.evidence_packages),'cross-workspace packages hidden');
select pg_temp.assert_true((select count(*)=0 from public.evidence_items),'cross-workspace items hidden');
select pg_temp.assert_true((select count(*)=0 from public.finding_occurrences),'cross-workspace occurrences hidden');
select pg_temp.assert_true((select count(*)=0 from public.finding_reviews),'cross-workspace reviews hidden');
select pg_temp.assert_true((select count(*)=0 from public.finding_audit_events),'cross-workspace audit hidden');
select pg_temp.expect_error('select public.derive_execution_evidence(current_setting(''ev.run'')::uuid)','42501','cross-tenant derivation');
select pg_temp.expect_error('select public.review_finding(current_setting(''ev.finding'')::uuid,1,''DISMISS'',''LOW'','''')','42501','cross-tenant review denied before stale disclosure');
reset role;
select pg_temp.assert_true((select bool_and(relrowsecurity) from pg_class where oid in ('public.evidence_packages'::regclass,'public.evidence_items'::regclass,'public.findings'::regclass,'public.finding_occurrences'::regclass,'public.finding_reviews'::regclass,'public.finding_audit_events'::regclass)),'all RLS enabled');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.derive_execution_evidence(uuid)','EXECUTE'),'runner unchanged');
select pg_temp.assert_true(not has_function_privilege('service_role','public.derive_execution_evidence(uuid)','EXECUTE'),'service default revoked');
select pg_temp.assert_true(not has_function_privilege('anon','public.review_finding(uuid,integer,text,text,text)','EXECUTE'),'anon review denied');
select pg_temp.expect_error('update public.evidence_packages set project_id=gen_random_uuid() where id=current_setting(''ev.package'')::uuid','23503','composite tenant binding');
select pg_temp.expect_error('update public.finding_occurrences set case_id=gen_random_uuid()','23503','cross-case occurrence FK');
select pg_temp.assert_true((select count(*)=5 from pg_proc p cross join lateral aclexplode(p.proacl) a where a.grantee=(select oid from pg_roles where rolname='testpilot_runner') and a.privilege_type='EXECUTE'),'exact five runner routines');
select set_config('ev.atomic',pg_temp.evidence_run('FAILED')::text,true);
create function pg_temp.fail_occurrence() returns trigger language plpgsql as $$ begin raise exception 'Disposable atomicity fixture' using errcode='P0001';end;$$;
create trigger local_atomicity_fixture before insert on public.finding_occurrences for each row execute function pg_temp.fail_occurrence();
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select pg_temp.expect_error('select public.derive_execution_evidence(current_setting(''ev.atomic'')::uuid)','P0001','real late derivation failure');
select pg_temp.assert_true((select count(*)=0 from public.evidence_packages where run_id=current_setting('ev.atomic')::uuid),'atomic no partial package');
select pg_temp.assert_true((select occurrence_count=3 from public.findings where id=current_setting('ev.finding')::uuid),'atomic count unchanged');
select pg_temp.assert_true((select count(*)=1 from public.execution_results where run_id=current_setting('ev.atomic')::uuid),'source result survives derivation failure');
reset role;
drop trigger local_atomicity_fixture on public.finding_occurrences;

-- A distinct approved assertion definition must not collapse into the prior finding.
select set_config('ev.different',pg_temp.evidence_run('FAILED',null,201)::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('ev.different')::uuid);
select pg_temp.assert_true((select count(*)=2 from public.findings where rule='ASSERTION_FAILED'),'materially different assertion has different logical finding');
select pg_temp.assert_true((select count(distinct fingerprint)=2 from public.findings where rule='ASSERTION_FAILED'),'distinct assertion fingerprints');
select pg_temp.assert_true((select count(distinct fingerprint)=count(*) from public.evidence_packages),'per-result evidence hashes distinct');
select pg_temp.assert_true((select p.fingerprint=encode(pg_catalog.sha256(pg_catalog.convert_to(jsonb_build_object('version','1','run',r.id,'workspace',r.workspace_id,'project',r.project_id,'environment',r.environment_id,'plan',r.plan_id,'scenario',r.scenario_id,'case',r.case_id,'config',r.config_id,'safety',jsonb_build_object('decision',r.decision,'policy',r.policy_version,'codes',r.reason_codes,'facts',r.facts),'caseReview',r.case_review_id,'scenarioReview',r.scenario_review_id,'request',r.request,'requestFingerprint',r.fingerprint,'result',v.result,'completed',to_char(r.completed_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))::text,'UTF8')),'hex') from public.evidence_packages p join public.execution_runs r on r.id=p.run_id join public.execution_results v on v.run_id=r.id where p.id=current_setting('ev.package')::uuid),'canonical persisted-source integrity hash reproducible');
select set_config('ev.pending',public.request_test_execution(current_setting('exec.case')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.expect_error('select public.derive_execution_evidence(current_setting(''ev.pending'')::uuid)','23514','nonterminal missing persisted result rejected');
select pg_temp.assert_true((select count(*)=0 from public.evidence_packages where run_id=current_setting('ev.pending')::uuid),'no evidence from missing persisted source');
reset role;


select set_config('ev.original_timezone',current_setting('TimeZone'),true);
set local time zone 'UTC';
select set_config('ev.utc_hash',(select encode(pg_catalog.sha256(pg_catalog.convert_to(jsonb_build_object('version','1','run',r.id,'workspace',r.workspace_id,'project',r.project_id,'environment',r.environment_id,'plan',r.plan_id,'scenario',r.scenario_id,'case',r.case_id,'config',r.config_id,'safety',jsonb_build_object('decision',r.decision,'policy',r.policy_version,'codes',r.reason_codes,'facts',r.facts),'caseReview',r.case_review_id,'scenarioReview',r.scenario_review_id,'request',r.request,'requestFingerprint',r.fingerprint,'result',v.result,'completed',to_char(r.completed_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))::text,'UTF8')),'hex') from public.execution_runs r join public.execution_results v on v.run_id=r.id where r.id=current_setting('ev.run')::uuid),true);
select pg_temp.assert_true((select fingerprint=current_setting('ev.utc_hash') from public.evidence_packages where id=current_setting('ev.package')::uuid),'stored actual hash matches canonical UTC oracle');
set local time zone 'Africa/Johannesburg';
select set_config('ev.joburg_hash',(select encode(pg_catalog.sha256(pg_catalog.convert_to(jsonb_build_object('version','1','run',r.id,'workspace',r.workspace_id,'project',r.project_id,'environment',r.environment_id,'plan',r.plan_id,'scenario',r.scenario_id,'case',r.case_id,'config',r.config_id,'safety',jsonb_build_object('decision',r.decision,'policy',r.policy_version,'codes',r.reason_codes,'facts',r.facts),'caseReview',r.case_review_id,'scenarioReview',r.scenario_review_id,'request',r.request,'requestFingerprint',r.fingerprint,'result',v.result,'completed',to_char(r.completed_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'))::text,'UTF8')),'hex') from public.execution_runs r join public.execution_results v on v.run_id=r.id where r.id=current_setting('ev.run')::uuid),true);
select pg_temp.assert_true(current_setting('ev.utc_hash')=current_setting('ev.joburg_hash'),'canonical manifest reproduces identically under both timezones');
select pg_temp.assert_true((select fingerprint=current_setting('ev.utc_hash') from public.evidence_packages where id=current_setting('ev.package')::uuid),'stored hash unchanged across timezone');
select pg_temp.assert_true((select to_char(completed_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')=(completed_at at time zone 'UTC')::date::text||'T'||to_char(completed_at at time zone 'UTC','HH24:MI:SS.US')||'Z' from public.execution_runs where id=current_setting('ev.run')::uuid),'UTC timestamp independent of session timezone');
select set_config('TimeZone',current_setting('ev.original_timezone'),true);
select public.validate_execution_runner_role();
select count(*) as m18_assertions_passed from pg_temp.qa_results;
rollback;
