-- Disposable local fixtures only. No HTTP or hosted changes.
\ir fixtures/curiosity-source.sql
truncate pg_temp.qa_results;
-- Select the reviewed analysis explicitly in this local fixture; old alternate proposal stays historical.
update public.qa_analyses set created_at=created_at-interval '1 day' where id<>current_setting('test.qa_first')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select pg_temp.assert_true(public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)=1,'one failed assertion observation');
select pg_temp.assert_true(public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)=0,'refresh retry deduplicates');
select pg_temp.assert_true((select count(*)=1 from public.memory_facts),'one logical fact');
select pg_temp.assert_true((select kind='ASSERTION_FAILURE_OBSERVED' and observation_count=1 from public.memory_facts),'failure bounded claim');
select pg_temp.assert_true((select currentness='CURRENT' from public.project_memory),'current source');
select pg_temp.assert_true((select count(*)=1 from public.memory_observations o join public.evidence_items e on e.id=o.evidence_item_id join public.evidence_packages p on p.id=o.package_id join public.execution_results r on r.run_id=o.run_id),'real item/package/result provenance');
select set_config('m.finding',(select finding_id::text from public.memory_facts),true);
select set_config('m.first',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true(public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)=current_setting('m.first')::uuid,'identical assessment dedup');
select pg_temp.assert_true((select scoring_version='api-quality-v1' from public.quality_assessments),'version persisted');
select pg_temp.assert_true((select result->'inputs'->>'knownOperations'='1' from public.quality_assessments),'known operation normalization');
select pg_temp.assert_true((select result->'inputs'->>'testedOperations'='1' from public.quality_assessments),'one asserted operation');
select pg_temp.assert_true((select result->'dimensions'->'execution'->>'score'='0' from public.quality_assessments),'failure execution health zero');
select pg_temp.assert_true((select result->>'confidence'='LOW' from public.quality_assessments),'one operation low confidence');
select pg_temp.assert_true((select result->'dimensions'->'requirements'->>'score'='100' from public.quality_assessments),'frozen requirement evidence coverage');
select pg_temp.assert_true((select result->'dimensions'->'risks'->>'score'='0' from public.quality_assessments),'unreviewed risk remains uncovered');
select pg_temp.assert_true((select result->'dimensions'->'freshness'->>'score'='100' from public.quality_assessments),'recent freshness');
select pg_temp.assert_true((select result->>'overall'='49' from public.quality_assessments),'exact baseline weighted score');
select set_config('m.original',(select result::text from public.quality_assessments),true);
select public.review_qa_item(current_setting('test.risk')::uuid,null,'APPROVE','',null,null);
reset role;
select set_config('m.repeat',pg_temp.evidence_run('FAILED')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts),'repeat same logical assertion');
select pg_temp.assert_true((select observation_count=2 from public.memory_facts),'repeat count increments');
select pg_temp.assert_true((select count(*)=2 from public.memory_observations),'historical provenance retained');
select public.review_finding(current_setting('m.finding')::uuid,0,'CONFIRM','HIGH','Reviewed declared assertion.');
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='FINDING_CONFIRMED'),'human confirmation remembered');
select pg_temp.assert_true((select review_id is not null from public.memory_observations where claim='CONFIRMED'),'review provenance');
select set_config('m.confirmed',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true((select result->'dimensions'->'findings'->>'score'='40' from public.quality_assessments where id=current_setting('m.confirmed')::uuid),'confirmed HIGH stronger penalty');
select pg_temp.assert_true((select count(*)=2 from public.quality_assessments),'changed state new snapshot');
select pg_temp.assert_true((select result->>'overall'='66' from public.quality_assessments where id=current_setting('m.confirmed')::uuid),'exact reviewed coverage and finding score');
select pg_temp.assert_true((select previous_id=current_setting('m.first')::uuid and assessment_id=current_setting('m.confirmed')::uuid from public.quality_heads),'previous distinct assessment');
select pg_temp.assert_true((select result=current_setting('m.original')::jsonb from public.quality_assessments where id=current_setting('m.first')::uuid),'old snapshot unchanged');
reset role;
select set_config('m.success',pg_temp.evidence_run('PASSED')::text,true);
select set_config('m.timeout',pg_temp.evidence_run('ERROR','TIMEOUT')::text,true);
select set_config('m.different',pg_temp.evidence_run('FAILED',null,201)::text,true);
select set_config('m.blocked',pg_temp.evidence_run('BLOCKED','SAFETY_BLOCKED')::text,true);
select set_config('m.cancelled',pg_temp.evidence_run('CANCELLED','CANCELLED')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='OPERATION_VERIFIED_SUCCESS'),'verified success supported');
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='EXECUTION_ERROR_OBSERVED'),'infrastructure separate');
select pg_temp.assert_true((select count(*)=2 from public.memory_facts where kind='ASSERTION_FAILURE_OBSERVED'),'materially different failure distinct');
select pg_temp.assert_true((select count(*)=0 from public.memory_observations where run_id in(current_setting('m.blocked')::uuid,current_setting('m.cancelled')::uuid)),'no verification from blocked/cancelled');
select pg_temp.assert_true((select currentness='SUPERSEDED' from public.project_memory where kind='OPERATION_VERIFIED_SUCCESS'),'later failure supersedes success without erasure');
select public.review_finding((select id from public.findings where rule='EXECUTION_TIMEOUT'),0,'DISMISS','INFO','Infrastructure dismissed.');
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='FINDING_DISMISSED'),'dismissal remembered');
reset role;
select set_config('m.timeout2',pg_temp.evidence_run('ERROR','TIMEOUT')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='FINDING_REOBSERVED'),'dismissed later reproduced recorded');
select pg_temp.assert_true((select status='DISMISSED' from public.findings where rule='EXECUTION_TIMEOUT'),'human dismissal not overridden');
select set_config('m.investigation',public.derive_investigation(current_setting('ev.run')::uuid)::text,true);
select public.refresh_investigation(current_setting('m.investigation')::uuid,false,true);
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where kind='INVESTIGATION_CONCLUDED'),'persisted stopped investigation remembered');
select pg_temp.assert_true((select claim='STOPPED_BY_POLICY' and investigation_id=current_setting('m.investigation')::uuid from public.memory_observations where investigation_id is not null),'conclusion not defect proof');
do $$ declare t text;verb text;begin foreach t in array array['memory_facts','memory_observations','quality_assessments','quality_heads'] loop
 perform pg_temp.assert_true((select relrowsecurity from pg_class where oid=('public.'||t)::regclass),'RLS enabled '||t);
 foreach verb in array array['INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] loop
 perform pg_temp.assert_true(not has_table_privilege('authenticated','public.'||t,verb),'auth no '||verb||' '||t);end loop;
 perform pg_temp.assert_true(not has_table_privilege('anon','public.'||t,'SELECT'),'anon read denied '||t);
 perform pg_temp.assert_true(not has_table_privilege('testpilot_runner','public.'||t,'SELECT,INSERT,UPDATE,DELETE'),'runner no authority '||t);
end loop;end;$$;
select pg_temp.expect_error('delete from public.memory_facts','42501','fact immutable');
select pg_temp.expect_error('insert into public.memory_observations default values','42501','browser cannot invent observations');
select pg_temp.expect_error('update public.quality_assessments set result=''{}''','42501','browser cannot choose scores');
select pg_temp.expect_error('delete from public.quality_heads','42501','browser cannot choose current snapshot');
select pg_temp.expect_error('select public.compute_api_quality(''{}'')','42501','private scoring helper denied');
select pg_temp.expect_error('select public.intelligence_inputs(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid)','42501','private input helper denied');
select pg_temp.expect_error('select public.refresh_project_memory(current_setting(''test.g_pa2'')::uuid,current_setting(''exec.environment'')::uuid)','23514','cross-project environment denied');
select pg_temp.expect_error('select public.assess_project_quality(current_setting(''test.g_pa'')::uuid,gen_random_uuid())','23514','unknown environment denied');
select pg_temp.assert_true((select count(*)=2 from pg_proc where proname in('refresh_project_memory','assess_project_quality') and prosecdef and proconfig=array['search_path=""']),'RPC secure definer search paths');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.assess_project_quality(uuid,uuid)','EXECUTE'),'runner no quality RPC');
select pg_temp.assert_true(not has_function_privilege('anon','public.refresh_project_memory(uuid,uuid)','EXECUTE'),'anon no refresh RPC');
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000002',true);
do $$ declare t text;begin foreach t in array array['memory_facts','memory_observations','quality_assessments','quality_heads','project_memory'] loop
 execute format('select pg_temp.assert_true(count(*)=0,%L) from public.%I','cross-workspace read '||t,t);end loop;end;$$;
select pg_temp.expect_error('select public.refresh_project_memory(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid)','42501','cross-tenant derivation denied');
select pg_temp.expect_error('select public.assess_project_quality(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid)','42501','cross-tenant assessment denied');
select set_config('request.jwt.claim.sub','',true);
select pg_temp.expect_error('select public.refresh_project_memory(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid)','42501','caller required');
reset role;
select pg_temp.expect_error('update public.memory_observations set package_id=gen_random_uuid()','23503','unknown evidence rejected');
select pg_temp.expect_error('update public.memory_observations set project_id=current_setting(''test.g_pa2'')::uuid','23503','cross-project provenance rejected');
select pg_temp.expect_error('update public.memory_observations set workspace_id=gen_random_uuid()','23503','cross-workspace provenance rejected');
select pg_temp.expect_error('update public.memory_observations set environment_id=(select id from public.environments where project_id=current_setting(''test.g_pa'')::uuid and type=''PRODUCTION'')','23503','cross-environment provenance rejected');
select pg_temp.expect_error('update public.memory_observations set claim=''Authorization: Bearer fixture''','23514','closed claims reject credentials');
select pg_temp.expect_error('update public.memory_facts set kind=''AI_NOTE''','23514','AI cannot author category');

select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
-- Local owner fixture time travel is never performed against hosted data.
update public.execution_runs set completed_at=current_timestamp-interval '8 days' where project_id=current_setting('test.g_pa')::uuid;
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'freshnessPoints'='50','aging evidence earns fifty points');
update public.execution_runs set completed_at=current_timestamp-interval '31 days' where project_id=current_setting('test.g_pa')::uuid;
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'freshnessPoints'='0','stale evidence earns zero');
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'testedOperations'='0','stale operations unverified');
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'findingPenalty'='60','staleness never silently resolves confirmed HIGH finding');
select pg_temp.assert_true(public.compute_api_quality(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid))->>'status'='UNKNOWN','stale-only project unknown');
-- Retain assertion results while restoring fixture timestamps for subsequent tests.
-- Restore source time explicitly (fixture only) rather than roll back successful assertions.
update public.execution_runs set completed_at=clock_timestamp() where project_id=current_setting('test.g_pa')::uuid;
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'coveredRiskWeight'='2','reviewed risk has causally subsequent evidence');
-- Identical logical state reuse remains correct after A -> B -> A.
select set_config('m.base',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
update public.findings set severity='CRITICAL' where id=current_setting('m.finding')::uuid;
select set_config('m.changed',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true(current_setting('m.base')<>current_setting('m.changed'),'changed severity changes fingerprint');
update public.findings set severity='HIGH' where id=current_setting('m.finding')::uuid;
select pg_temp.assert_true(public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)=current_setting('m.base')::uuid,'state cycle reuses immutable snapshot');
select pg_temp.assert_true((select assessment_id=current_setting('m.base')::uuid and previous_id=current_setting('m.changed')::uuid from public.quality_heads),'state cycle current and previous correct');
-- Production environment observes its own run, not development verification.
select set_config('m.dev',current_setting('exec.environment'),true);
select set_config('exec.environment',(select id::text from public.environments where project_id=current_setting('test.g_pa')::uuid and type='PRODUCTION'),true);
set local role authenticated;
select public.configure_execution_environment(current_setting('exec.environment')::uuid,'https://api.example.test/',443,true);
reset role;
select set_config('m.production',pg_temp.evidence_run('PASSED')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select pg_temp.assert_true((select count(*)=1 from public.memory_facts where environment_id=current_setting('exec.environment')::uuid),'production fact separately scoped');
select pg_temp.assert_true((select observation_count=1 from public.memory_facts where environment_id=current_setting('exec.environment')::uuid),'development counts not merged');
select set_config('m.prodassessment',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true((select result->'inputs'->>'findingPenalty'='0' from public.quality_assessments where id=current_setting('m.prodassessment')::uuid),'development findings not production penalty');
select pg_temp.assert_true((select result->>'overall'='100' and result->>'confidence'='LOW' from public.quality_assessments where id=current_setting('m.prodassessment')::uuid),'production success exact score with low confidence');
select set_config('exec.environment',current_setting('m.dev'),true);
reset role;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
set local role authenticated;
reset role;
update public.api_imports set created_at=created_at-interval '1 day' where id=current_setting('test.g_import')::uuid;
set local role authenticated;
select set_config('m.newsource',public.import_api_spec(current_setting('test.g_wa')::uuid,current_setting('test.g_pa')::uuid,'json',null,100,repeat('b',64),'{"info":{}}','{"modelVersion":1,"title":"Local memory version fixture","version":"2","openapiVersion":"3.0.3","operations":[],"components":{}}')::text,true);
select pg_temp.assert_true((select bool_and(currentness='HISTORICAL') from public.project_memory),'old source historical after reimport');
select set_config('m.newassessment',public.assess_project_quality(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true((select result->'overall'='null'::jsonb and result->>'status'='UNKNOWN' from public.quality_assessments where id=current_setting('m.newassessment')::uuid),'new source cannot inherit old verification');
select pg_temp.assert_true((select result->'inputs'->>'testedOperations'='0' from public.quality_assessments where id=current_setting('m.newassessment')::uuid),'no tested new-source operations');
reset role;
select pg_temp.assert_true(public.compute_api_quality('{"knownOperations":9,"testedOperations":3,"activeRequirements":8,"coveredRequirements":1,"riskWeight":6,"coveredRiskWeight":3,"executionPoints":300,"findingPenalty":67.5,"freshnessPoints":300}') ->>'sufficiency'='33','exact rational half tie preserved');
select public.validate_execution_runner_role();
select count(*) as m110_assertions_passed from pg_temp.qa_results;
rollback;
