-- Authoritative scoped signals on disposable local records only.
\ir fixtures/curiosity-source.sql
truncate pg_temp.qa_results;
update public.qa_analyses set created_at=created_at-interval '1 day' where id<>current_setting('test.qa_first')::uuid;
update public.qa_items set severity='HIGH' where id=current_setting('test.risk')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select set_config('r.release',public.create_release(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid,'Local signal release')::text,true);
select set_config('r.uncovered',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select result->'unknowns' @> jsonb_build_array(jsonb_build_object('code','UNCOVERED_HIGH_RISK','ids',jsonb_build_array(current_setting('test.risk')))) from public.release_assessments where id=current_setting('r.uncovered')::uuid),'uncovered HIGH risk explicit');
select public.review_qa_item(current_setting('test.risk')::uuid,null,'APPROVE','',null,null);
reset role;
select set_config('r.failed',pg_temp.evidence_run('FAILED')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select set_config('r.failed_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select result->>'status'='BLOCKED' and result->'blockers' @> jsonb_build_array(jsonb_build_object('code','FAILED_HIGH_RISK','ids',jsonb_build_array(current_setting('test.risk'),current_setting('r.failed')))) from public.release_assessments where id=current_setting('r.failed_a')::uuid),'approved HIGH risk current failed evidence blocks');
select pg_temp.assert_true((select result->'warnings' @> jsonb_build_array(jsonb_build_object('code','RECURRING_CURRENT_FAILURE')) from public.release_assessments where id=current_setting('r.failed_a')::uuid),'current repeated failure memory adds warning');
select pg_temp.assert_true((select result->'inputs'->'quality'->'result'->'inputs'->>'coveredRiskWeight'='4' from public.release_assessments where id=current_setting('r.failed_a')::uuid),'risk weight and coverage reused from M110');
reset role;
select set_config('r.error',pg_temp.evidence_run('ERROR','TIMEOUT')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select set_config('r.error_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select result->'warnings' @> jsonb_build_array(jsonb_build_object('code','INFRASTRUCTURE_ERROR','ids',jsonb_build_array(current_setting('r.error')))) from public.release_assessments where id=current_setting('r.error_a')::uuid),'infrastructure warning references actual ERROR');
select pg_temp.assert_true((select result->'blockers' @> jsonb_build_array(jsonb_build_object('code','FAILED_HIGH_RISK')) from public.release_assessments where id=current_setting('r.error_a')::uuid),'infrastructure error does not erase last asserted risk failure');
select set_config('r.investigation',public.derive_investigation(current_setting('r.error')::uuid)::text,true);
select set_config('r.open_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select result->'unknowns' @> jsonb_build_array(jsonb_build_object('code','OPEN_INVESTIGATION','ids',jsonb_build_array(current_setting('r.investigation')))) from public.release_assessments where id=current_setting('r.open_a')::uuid),'open investigation unresolved');
select public.refresh_investigation(current_setting('r.investigation')::uuid,false,true);
select set_config('r.stop_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true(current_setting('r.stop_a')<>current_setting('r.open_a'),'investigation conclusion changes fingerprint');
select pg_temp.assert_true((select result->'warnings' @> jsonb_build_array(jsonb_build_object('code','INCONCLUSIVE_INVESTIGATION','ids',jsonb_build_array(current_setting('r.investigation')))) from public.release_assessments where id=current_setting('r.stop_a')::uuid),'stopped investigation honest warning');
reset role;
select set_config('r.pass',pg_temp.evidence_run('PASSED')::text,true);
set local role authenticated;
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select set_config('r.pass_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select not(result->'blockers' @> jsonb_build_array(jsonb_build_object('code','FAILED_HIGH_RISK'))) from public.release_assessments where id=current_setting('r.pass_a')::uuid),'later asserted success replaces risk failure');
select pg_temp.assert_true((select not(result->'warnings' @> jsonb_build_array(jsonb_build_object('code','RECURRING_CURRENT_FAILURE'))) from public.release_assessments where id=current_setting('r.pass_a')::uuid),'superseded historical memory cannot override current success');
select pg_temp.assert_true((select result->'inputs'->'runs'->0->>'outcome'='PASS' from public.release_assessments where id=current_setting('r.pass_a')::uuid),'latest actual PASS summarized');
select set_config('r.finding',(select id::text from public.findings limit 1),true);
select public.review_finding(current_setting('r.finding')::uuid,0,'DISMISS','MEDIUM','Reviewed and dismissed observation.');
select set_config('r.dismissed_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select jsonb_array_length(result->'blockers')=0 and result->'inputs'->'findings' @> jsonb_build_array(jsonb_build_object('id',current_setting('r.finding'),'status','DISMISSED')) from public.release_assessments where id=current_setting('r.dismissed_a')::uuid),'dismissal preserved, never blocker');
select set_config('r.report',public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.dismissed_a')::uuid)::text,true);
select pg_temp.assert_true((select decision_id is null and snapshot->'decision'='null'::jsonb from public.release_reports),'undecided report stays undecided');
select pg_temp.assert_true(public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.dismissed_a')::uuid)=current_setting('r.report')::uuid,'null decision report deduplication');
reset role;
-- Synthetic URI fixture is permitted in local source, never in persisted reports.
select set_config('r.unsafe',jsonb_build_array('OPERATION','GET /postgresql://fixture:fixture@db.example.invalid/db')::text,true);
insert into public.behaviour_graph_nodes(graph_id,logical_id,api_import_id,project_id,workspace_id,type,label,provenance) select graph_id,current_setting('r.unsafe'),api_import_id,project_id,workspace_id,type,label,provenance from public.behaviour_graph_nodes where graph_id=current_setting('test.g_first')::uuid and logical_id='["OPERATION","GET /users"]';
update public.api_imports set knowledge=jsonb_set(jsonb_set(knowledge,'{operations,0,path}',to_jsonb('/postgresql://fixture:fixture@db.example.invalid/db'::text)),'{operations,0,key}',to_jsonb('GET /postgresql://fixture:fixture@db.example.invalid/db'::text)) where id=current_setting('test.g_import')::uuid;
update public.test_item_nodes set node_id=current_setting('r.unsafe') where item_id=current_setting('exec.case')::uuid and node_id='["OPERATION","GET /users"]';
set local role authenticated;
select set_config('r.safe_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select set_config('r.safe_report',public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.safe_a')::uuid)::text,true);
select pg_temp.assert_true(not exists(select 1 from public.release_assessments a where to_jsonb(a)::text like '%fixture:fixture%'),'unsafe operation never copied into assessment');
select pg_temp.assert_true(not exists(select 1 from public.release_reports a where to_jsonb(a)::text like '%fixture:fixture%'),'unsafe operation never copied into report');
select pg_temp.assert_true(not exists(select 1 from public.release_audit_events a where to_jsonb(a)::text like '%fixture:fixture%'),'audit contains no raw credential');
reset role;
select count(*) as m111_signal_assertions_passed from pg_temp.qa_results;
rollback;
