-- Disposable local PostgreSQL fixtures only; no HTTP, AI or hosted writes.
\ir fixtures/curiosity-source.sql
truncate pg_temp.qa_results;
update public.qa_analyses set created_at=created_at-interval '1 day' where id<>current_setting('test.qa_first')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select public.refresh_project_memory(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid);
select set_config('r.release',public.create_release(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid,'Local release fixture')::text,true);
select pg_temp.assert_true((select api_import_id=current_setting('test.g_import')::uuid and created_by=auth.uid() and assessment_id is null from public.releases),'human scope pinned to current source');
select pg_temp.expect_error('select public.create_release(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid,''postgresql://fixture:fixture@db.example.invalid/db'')','23514','credential release name rejected');
select set_config('r.a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true(public.assess_release(current_setting('r.release')::uuid)=current_setting('r.a')::uuid,'assessment retry deduplicates');
select pg_temp.assert_true((select count(*)=1 from public.release_assessments),'one logical assessment');
select pg_temp.assert_true((select result->>'status'='INSUFFICIENT_EVIDENCE' from public.release_assessments),'narrow evidence cannot imply clear');
select pg_temp.assert_true((select quality_assessment_id is not null and result->'inputs'->'quality'->>'scoring_version'='api-quality-v1' from public.release_assessments),'compatible immutable M110 quality used');
select pg_temp.assert_true((select result->'inputs'->'quality'->'result'->'inputs'->>'coveredRequirements'='1' from public.release_assessments),'frozen approved requirement coverage reused');
select pg_temp.assert_true((select jsonb_array_length(result->'inputs'->'runs')=1 and result->'inputs'->'runs'->0->>'outcome'='FAIL' from public.release_assessments),'actual assertion failure summary');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid,null,''APPROVE'','''')','23514','insufficient ordinary approval denied');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid,null,''APPROVE_WITH_RISK'','''')','23514','override requires rationale');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid,null,''APPROVE_WITH_RISK'',''password=fixture'')','23514','decision credential rejected');
select set_config('r.d',public.decide_release(current_setting('r.release')::uuid,current_setting('r.a')::uuid,null,'APPROVE_WITH_RISK','Accepting documented fixture risk.')::text,true);
select pg_temp.assert_true((select is_override and actor_id=auth.uid() and assessment_id=current_setting('r.a')::uuid from public.release_decisions),'override exact assessment and actor preserved');
select pg_temp.assert_true((select result->>'status'='INSUFFICIENT_EVIDENCE' from public.release_assessments),'human decision never rewrites assessment');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid,null,''REJECT'',''Stale review.'')','40001','stale decision rejected');
select set_config('r.report',public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.a')::uuid)::text,true);
select pg_temp.assert_true(public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.a')::uuid)=current_setting('r.report')::uuid,'report deduplicates');
select set_config('r.original',(select snapshot::text from public.release_reports where id=current_setting('r.report')::uuid),true);
select pg_temp.assert_true((select snapshot->>'reportVersion'='release-report-v1' and snapshot->'assessment'->>'policy_version'='release-policy-v1' from public.release_reports),'report and policy versions exact');
select pg_temp.assert_true((select snapshot->'decision'->>'id'=current_setting('r.d') and snapshot->'decision'->>'rationale'='Accepting documented fixture risk.' from public.release_reports),'report decision and rationale exact');
select pg_temp.assert_true((select snapshot->'assessment'->'result'->'inputs'->'quality'=(select result->'inputs'->'quality' from public.release_assessments where id=current_setting('r.a')::uuid) from public.release_reports),'report quality dimensions and sufficiency exact');
select pg_temp.assert_true((select snapshot->'release'->>'api_import_id'=current_setting('test.g_import') and snapshot->'release'->>'environment_id'=current_setting('exec.environment') and snapshot->>'environmentType'='DEVELOPMENT' from public.release_reports),'report scope exact');
select set_config('r.finding',(select id::text from public.findings limit 1),true);
select public.review_finding(current_setting('r.finding')::uuid,0,'CONFIRM','CRITICAL','Reviewed declared assertion.');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid,current_setting(''r.d'')::uuid,''REJECT'',''Changed evidence.'')','40001','new finding review invalidates stale assessment decision');
select set_config('r.b',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true(current_setting('r.b')<>current_setting('r.a'),'finding change creates assessment');
select pg_temp.assert_true((select result->>'status'='BLOCKED' and jsonb_array_length(result->'blockers')=1 from public.release_assessments where id=current_setting('r.b')::uuid),'confirmed critical blocks despite insufficiency');
select pg_temp.assert_true((select snapshot=current_setting('r.original')::jsonb from public.release_reports where id=current_setting('r.report')::uuid),'historical report unchanged by finding review');
select set_config('r.d2',public.decide_release(current_setting('r.release')::uuid,current_setting('r.b')::uuid,current_setting('r.d')::uuid,'REJECT','Confirmed blocker requires investigation.')::text,true);
select pg_temp.assert_true((select count(*)=2 and max(revision)=2 from public.release_decisions),'decision replacement is append-only');
select pg_temp.assert_true((select snapshot=current_setting('r.original')::jsonb from public.release_reports where id=current_setting('r.report')::uuid),'historical report retains old decision');
select set_config('r.report2',public.generate_release_report(current_setting('r.release')::uuid,current_setting('r.b')::uuid)::text,true);
select pg_temp.assert_true(current_setting('r.report2')<>current_setting('r.report'),'changed assessment decision creates report');
select pg_temp.assert_true(not exists(select 1 from public.release_audit_events where event='RELEASE_ASSESSED' and assessment_id is null or event='RELEASE_DECISION_RECORDED' and decision_id is null or event='RELEASE_REPORT_GENERATED' and report_id is null),'audit references exact immutable state');
do $$declare relation text;begin foreach relation in array array['releases','release_assessments','release_decisions','release_reports','release_audit_events'] loop
 perform pg_temp.expect_error(format('update public.%I set project_id=project_id',relation),'42501',relation||' direct update denied');
 perform pg_temp.expect_error(format('delete from public.%I',relation),'42501',relation||' direct delete denied');
 perform pg_temp.expect_error(format('insert into public.%I select * from public.%I limit 1',relation,relation),'42501',relation||' direct insert denied');end loop;end;$$;
select pg_temp.expect_error('select public.compute_release_policy(''{}'')','42501','policy helper inaccessible');
select pg_temp.expect_error('select public.release_inputs((select r from public.releases r limit 1),null)','42501','input helper inaccessible');
select set_config('request.jwt.claim.sub','',true);
select pg_temp.expect_error('select public.assess_release(current_setting(''r.release'')::uuid)','42501','authenticated role without caller identity denied');
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000002',true);
select pg_temp.assert_true((select count(*)=0 from public.releases),'cross-workspace releases invisible');
select pg_temp.assert_true((select count(*)=0 from public.release_reports),'cross-workspace reports invisible');
select pg_temp.expect_error('select public.assess_release(current_setting(''r.release'')::uuid)','42501','cross-workspace assessment denied');
select pg_temp.expect_error('select public.generate_release_report(current_setting(''r.release'')::uuid,current_setting(''r.a'')::uuid)','42501','cross-workspace report denied');
reset role;
insert into public.workspace_members(workspace_id,user_id,role) values(current_setting('test.g_wa')::uuid,'14000000-0000-0000-0000-000000000002','MEMBER');
set local role authenticated;
select pg_temp.assert_true((select count(*)=1 from public.releases),'MEMBER can read');
select pg_temp.expect_error('select public.create_release(current_setting(''test.g_pa'')::uuid,current_setting(''exec.environment'')::uuid,''Member attempt'')','42501','MEMBER creation denied');
select pg_temp.expect_error('select public.assess_release(current_setting(''r.release'')::uuid)','42501','MEMBER assessment denied');
select pg_temp.expect_error('select public.decide_release(current_setting(''r.release'')::uuid,current_setting(''r.b'')::uuid,current_setting(''r.d2'')::uuid,''REJECT'',''Member attempt.'')','42501','MEMBER decision denied');
select pg_temp.expect_error('select public.generate_release_report(current_setting(''r.release'')::uuid,current_setting(''r.b'')::uuid)','42501','MEMBER official report denied');
reset role;
update public.workspace_members set role='ADMIN' where workspace_id=current_setting('test.g_wa')::uuid and user_id='14000000-0000-0000-0000-000000000002';
set local role authenticated;
select set_config('r.admin',public.create_release(current_setting('test.g_pa2')::uuid,(select id from public.environments where project_id=current_setting('test.g_pa2')::uuid and type='DEVELOPMENT'),'Local admin fixture')::text,true);
select pg_temp.assert_true((select created_by=auth.uid() from public.releases where id=current_setting('r.admin')::uuid),'ADMIN authority positive');
reset role;
select pg_temp.assert_true(not has_table_privilege('anon','public.release_reports','SELECT'),'anon reads denied');
select pg_temp.assert_true(not has_function_privilege('anon','public.assess_release(uuid)','EXECUTE'),'anon RPC denied');
select pg_temp.expect_error('update public.releases set project_id=current_setting(''test.g_pa2'')::uuid','23503','release project substitution rejected');
select pg_temp.expect_error('update public.release_assessments set environment_id=(select id from public.environments where project_id=current_setting(''test.g_pa'')::uuid and type=''PRODUCTION'')','23503','assessment environment substitution rejected');
select pg_temp.expect_error('update public.release_assessments set api_import_id=current_setting(''test.g_import2'')::uuid','23503','assessment source substitution rejected');
select pg_temp.expect_error('update public.release_reports set assessment_id=current_setting(''r.b'')::uuid where id=current_setting(''r.report'')::uuid','23503','report decision assessment mismatch rejected');
select pg_temp.assert_true(not exists(select 1 from pg_class c where c.relname in ('releases','release_assessments','release_decisions','release_reports','release_audit_events') and not c.relrowsecurity),'release relations RLS enabled');
select pg_temp.assert_true(not exists(select 1 from pg_class c where c.relname in ('releases','release_assessments','release_decisions','release_reports','release_audit_events') and has_table_privilege('testpilot_runner',c.oid,'SELECT,INSERT,UPDATE,DELETE')),'runner release table access denied');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.assess_release(uuid)','EXECUTE'),'runner release RPC denied');
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select set_config('r.prod',public.create_release(current_setting('test.g_pa')::uuid,(select id from public.environments where project_id=current_setting('test.g_pa')::uuid and type='PRODUCTION'),'Local production fixture')::text,true);
select set_config('r.prod_a',public.assess_release(current_setting('r.prod')::uuid)::text,true);
select pg_temp.assert_true((select result->>'status'='INSUFFICIENT_EVIDENCE' and jsonb_array_length(result->'inputs'->'findings')=0 and jsonb_array_length(result->'inputs'->'memory')=0 and jsonb_array_length(result->'inputs'->'runs')=0 from public.release_assessments where id=current_setting('r.prod_a')::uuid),'Development cannot verify or block Production');
reset role;
select pg_temp.expect_error('update public.release_assessments set quality_assessment_id=(select quality_assessment_id from public.release_assessments where id=current_setting(''r.prod_a'')::uuid) where id=current_setting(''r.a'')::uuid','23503','incompatible quality environment independently denied');
set local role authenticated;
select pg_temp.expect_error('select public.generate_release_report(current_setting(''r.release'')::uuid,current_setting(''r.prod_a'')::uuid)','42501','cross-release assessment rejected');
reset role;
update public.api_imports set created_at=created_at-interval '1 day' where id=current_setting('test.g_import')::uuid;
set local role authenticated;
select set_config('r.newsource',public.import_api_spec(current_setting('test.g_wa')::uuid,current_setting('test.g_pa')::uuid,'json',null,100,repeat('b',64),'{"info":{}}','{"modelVersion":1,"title":"Local version fixture","version":"2","openapiVersion":"3.0.3","operations":[],"components":{}}')::text,true);
select set_config('r.new',public.create_release(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid,'Local new version fixture')::text,true);
select set_config('r.new_a',public.assess_release(current_setting('r.new')::uuid)::text,true);
select pg_temp.assert_true((select result->>'status'='INSUFFICIENT_EVIDENCE' and jsonb_array_length(result->'inputs'->'findings')=0 and result->'inputs'->'quality'->'result'->>'overall' is null from public.release_assessments where id=current_setting('r.new_a')::uuid),'new source cannot inherit old evidence or finding');
select set_config('r.historical_a',public.assess_release(current_setting('r.release')::uuid)::text,true);
select pg_temp.assert_true((select result->'inputs'->'sourceCurrent'='false'::jsonb and result->'inputs'->'quality'='null'::jsonb from public.release_assessments where id=current_setting('r.historical_a')::uuid),'old release quality incompatible');
select pg_temp.assert_true((select snapshot=current_setting('r.original')::jsonb from public.release_reports where id=current_setting('r.report')::uuid),'report immutable after reimport');
reset role;
select public.validate_execution_runner_role();
select count(*) as m111_assertions_passed from pg_temp.qa_results;
rollback;
