-- Local rollback-only downstream delivery-uncertainty regression.
\ir fixtures/curiosity-source.sql
truncate pg_temp.qa_results;
grant all on pg_temp.qa_results to testpilot_runner;
select set_config('recovery.pass',pg_temp.evidence_run('PASSED')::text,true);
set local role authenticated;
select public.derive_execution_evidence(current_setting('recovery.pass')::uuid);
reset role;
select set_config('recovery.before',public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true(current_setting('recovery.before')::jsonb->>'executionPoints'='100','prior successful evidence contributes real health');
select set_config('recovery.transport',pg_temp.evidence_run('ERROR','TRANSPORT_FAILURE')::text,true);
select pg_temp.assert_true(public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)->>'executionPoints'='0','persisted uncertain transport without derived evidence cannot retain prior positive health');
select pg_temp.assert_true(not exists(select 1 from public.evidence_packages where run_id=current_setting('recovery.transport')::uuid),'undelivered observation is not fabricated evidence');
set local role authenticated;
select set_config('recovery.run',public.request_test_execution(current_setting('exec.case')::uuid,current_setting('exec.environment')::uuid)::text,true);
set local role testpilot_runner;
select set_config('recovery.job',public.claim_test_execution()::text,true);
select public.record_execution_safety(current_setting('recovery.run')::uuid,(current_setting('recovery.job')::jsonb->'run'->>'claim_token')::uuid,'ALLOW','[]','{}','{"method":"GET","url":"https://api.example.test/","headers":{},"body":null,"assertions":[],"operationPointer":"#/info"}',repeat('a',64));
select set_config('recovery.job',public.claim_test_execution()::text,true);
select pg_temp.assert_true(public.authorize_execution_send(current_setting('recovery.run')::uuid,(current_setting('recovery.job')::jsonb->'run'->>'claim_token')::uuid,repeat('a',64),current_setting('exec.config')::uuid,'1.0.0'),'durable intent committed before simulated crash');
reset role;
update public.execution_runs set claim_expires_at=clock_timestamp()-interval '1 second' where id=current_setting('recovery.run')::uuid;
set local role testpilot_runner;
select public.claim_test_execution();
reset role;
select set_config('recovery.after',public.intelligence_inputs(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid)::text,true);
select pg_temp.assert_true(current_setting('recovery.after')::jsonb->>'executionPoints'='0','unknown completion cannot inherit prior positive execution health');
select pg_temp.assert_true(current_setting('recovery.after')::jsonb->'provenance'->'runIds' ? current_setting('recovery.run'),'unknown run retained in authoritative quality provenance');
select pg_temp.assert_true(current_setting('recovery.before')::jsonb->'provenance'->>'stateHash'<>current_setting('recovery.after')::jsonb->'provenance'->>'stateHash','unknown delivery invalidates cached quality fingerprint');
select pg_temp.assert_true(not exists(select 1 from public.execution_results where run_id=current_setting('recovery.run')::uuid),'unknown recovery fabricates no terminal result');
select pg_temp.assert_true(not exists(select 1 from public.evidence_packages where run_id=current_setting('recovery.run')::uuid),'unknown recovery fabricates no evidence');
select pg_temp.assert_true(not exists(select 1 from public.findings f join public.evidence_packages e on e.id=f.first_package_id where e.run_id=current_setting('recovery.run')::uuid),'unknown recovery fabricates no defect');
set local role authenticated;
select pg_temp.expect_error('select public.derive_execution_evidence(current_setting(''recovery.run'')::uuid)','23514','no evidence derivation without observed result');
select set_config('recovery.release',public.create_release(current_setting('test.g_pa')::uuid,current_setting('exec.environment')::uuid,'Recovery regression fixture')::text,true);
select set_config('recovery.assessment',public.assess_release(current_setting('recovery.release')::uuid)::text,true);
select pg_temp.assert_true((select result->'unknowns' @> jsonb_build_array(jsonb_build_object('code','INDETERMINATE_EXECUTION','ids',jsonb_build_array(current_setting('recovery.run')))) and result->>'status'<>'CLEAR' from public.release_assessments where id=current_setting('recovery.assessment')::uuid),'authoritative release assessment exposes delivery uncertainty and cannot be CLEAR');
reset role;
select pg_temp.assert_true(not public.intelligence_inputs(current_setting('test.g_pa')::uuid,(select id from public.environments where project_id=current_setting('test.g_pa')::uuid and type='PRODUCTION'))->'provenance'->'runIds' ? current_setting('recovery.run'),'unknown run cannot leak across environment inputs');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.intelligence_inputs(uuid,uuid)','EXECUTE') and not has_function_privilege('authenticated','public.release_inputs(public.releases,uuid)','EXECUTE') and not has_function_privilege('anon','public.compute_release_policy(jsonb)','EXECUTE'),'updated private input functions preserve restricted ACLs');
select count(*) as runner_recovery_downstream_assertions from pg_temp.qa_results;
rollback;
