-- Disposable local-only runner recovery assertions; never hosted.
\ir fixtures/execution-source.sql
truncate pg_temp.qa_results;
grant all on pg_temp.qa_results to testpilot_runner;
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
select set_config('exec.case',(select id::text from public.test_items where plan_id=current_setting('test.eligible')::uuid and kind='CASE'),true);
select public.review_test_item((select scenario_id from public.test_items where id=current_setting('exec.case')::uuid),null,'APPROVE','',null,null,null);
select public.review_test_item(current_setting('exec.case')::uuid,null,'APPROVE','',null,null,null);
select set_config('exec.environment',(select id::text from public.environments where project_id=current_setting('test.g_pa')::uuid and type='DEVELOPMENT'),true);
select set_config('exec.config',public.configure_execution_environment(current_setting('exec.environment')::uuid,'https://api.example.test/',443,true)::text,true);
reset role;
create function pg_temp.recovery_job() returns jsonb language plpgsql as $$
declare run_id uuid;job jsonb;
begin
 execute 'set local role authenticated';perform set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000001',true);
 run_id:=public.request_test_execution(current_setting('exec.case')::uuid,current_setting('exec.environment')::uuid);
 execute 'set local role testpilot_runner';job:=public.claim_test_execution();
 perform public.record_execution_safety(run_id,(job->'run'->>'claim_token')::uuid,'ALLOW','[]','{}','{"method":"GET","url":"https://api.example.test/","headers":{},"body":null,"assertions":[],"operationPointer":"#/info"}',repeat('a',64));
 job:=public.claim_test_execution();execute 'reset role';return job;
end;$$;

select set_config('recovery.job',pg_temp.recovery_job()::text,true);
select set_config('recovery.id',(current_setting('recovery.job')::jsonb->'run'->>'id'),true);
select set_config('recovery.token',(current_setting('recovery.job')::jsonb->'run'->>'claim_token'),true);
select pg_temp.assert_true((select claim_generation=2 and claim_expires_at>clock_timestamp() and claim_started_at is not null from public.execution_runs where id=current_setting('recovery.id')::uuid),'two atomic claim generations and lease');
set local role testpilot_runner;
select pg_temp.assert_true(public.claim_test_execution() is null,'active claim excluded');
select pg_temp.assert_true(public.execution_cancel_requested(current_setting('recovery.id')::uuid,gen_random_uuid()),'foreign nonce cannot renew');
select pg_temp.assert_true(not public.execution_cancel_requested(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid),'owned lease renewed');
select pg_temp.assert_true(not public.authorize_execution_send(current_setting('recovery.id')::uuid,gen_random_uuid(),repeat('a',64),current_setting('exec.config')::uuid,'1.0.0'),'foreign nonce cannot authorize');
reset role;
update public.execution_runs set claim_expires_at=clock_timestamp()-interval '1 second' where id=current_setting('recovery.id')::uuid;
set local role testpilot_runner;
select pg_temp.assert_true(public.execution_cancel_requested(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid),'expired nonce cannot resurrect');
select pg_temp.assert_true(not public.authorize_execution_send(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid,repeat('a',64),current_setting('exec.config')::uuid,'1.0.0'),'expired nonce cannot send');
reset role;
select pg_temp.expect_error('set local role testpilot_runner;select public.finish_test_execution(current_setting(''recovery.id'')::uuid,current_setting(''recovery.token'')::uuid,''{"outcome":"ERROR","failure":"TRANSPORT_FAILURE","response":null,"assertions":[],"sent":false}'')','23514','expired nonce cannot persist');
set local role testpilot_runner;
select set_config('recovery.new',public.claim_test_execution()::text,true);
reset role;
select pg_temp.assert_true(current_setting('recovery.new')::jsonb->'run'->>'status'='SAFETY_REVIEW','unsent recovery reruns safety');
select pg_temp.assert_true(current_setting('recovery.new')::jsonb->'run'->>'claim_token'<>current_setting('recovery.token'),'new claim nonce fences old worker');
select pg_temp.assert_true((select claim_generation=3 and claim_recoveries=1 and approved_by is null and decision is null and send_authorized_at is null from public.execution_runs where id=current_setting('recovery.id')::uuid),'recovery clears authority without send evidence');
select pg_temp.assert_true((select count(*)=1 from public.execution_recovery_events where run_id=current_setting('recovery.id')::uuid and event='RECOVERED_UNSENT'),'unsent recovery audited once');
update public.execution_runs set status='CANCELLED',claim_token=null,claim_expires_at=null where id=current_setting('recovery.id')::uuid;
select set_config('recovery.job',pg_temp.recovery_job()::text,true);
select set_config('recovery.id',(current_setting('recovery.job')::jsonb->'run'->>'id'),true);
select set_config('recovery.token',(current_setting('recovery.job')::jsonb->'run'->>'claim_token'),true);
set local role testpilot_runner;
select pg_temp.assert_true(public.authorize_execution_send(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid,repeat('a',64),current_setting('exec.config')::uuid,'1.0.0'),'one durable send intent');
select pg_temp.assert_true(not public.authorize_execution_send(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid,repeat('a',64),current_setting('exec.config')::uuid,'1.0.0'),'intent cannot be reused');
reset role;
update public.execution_runs set claim_expires_at=clock_timestamp()-interval '1 second' where id=current_setting('recovery.id')::uuid;
set local role testpilot_runner;
select pg_temp.assert_true(public.claim_test_execution() is null,'possibly sent execution never reclaimed');
select pg_temp.assert_true(public.claim_test_execution() is null,'repeated recovery remains terminal');
reset role;
select pg_temp.assert_true((select status='ERROR' and recovery_outcome='INDETERMINATE' and send_authorized_at is not null and claim_token is null from public.execution_runs where id=current_setting('recovery.id')::uuid),'send ambiguity explicitly preserved');
select pg_temp.assert_true((select count(*)=0 from public.execution_results where run_id=current_setting('recovery.id')::uuid),'recovery manufactures no result');
select pg_temp.assert_true((select count(*)=1 from public.execution_recovery_events where run_id=current_setting('recovery.id')::uuid and event='RECOVERY_INDETERMINATE'),'terminal recovery audit idempotent');
select pg_temp.expect_error('set local role testpilot_runner;select public.finish_test_execution(current_setting(''recovery.id'')::uuid,current_setting(''recovery.token'')::uuid,''{"outcome":"ERROR","failure":"TRANSPORT_FAILURE","response":null,"assertions":[],"sent":true}'')','23514','stale completion cannot replace recovered outcome');
select set_config('recovery.job',pg_temp.recovery_job()::text,true);
select set_config('recovery.id',(current_setting('recovery.job')::jsonb->'run'->>'id'),true);
select set_config('recovery.token',(current_setting('recovery.job')::jsonb->'run'->>'claim_token'),true);
set local role testpilot_runner;
select public.finish_test_execution(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid,'{"outcome":"ERROR","failure":"TRANSPORT_FAILURE","response":null,"assertions":[],"sent":false}');
select public.finish_test_execution(current_setting('recovery.id')::uuid,current_setting('recovery.token')::uuid,'{"outcome":"ERROR","failure":"TRANSPORT_FAILURE","response":null,"assertions":[],"sent":false}');
reset role;
select pg_temp.assert_true((select count(*)=1 from public.execution_results where run_id=current_setting('recovery.id')::uuid),'lost acknowledgment retry persists once');
select pg_temp.expect_error('set local role testpilot_runner;select public.finish_test_execution(current_setting(''recovery.id'')::uuid,current_setting(''recovery.token'')::uuid,''{"outcome":"ERROR","failure":"TIMEOUT","response":null,"assertions":[],"sent":false}'')','23514','idempotency rejects changed result');
select set_config('recovery.job',pg_temp.recovery_job()::text,true);
select set_config('recovery.id',(current_setting('recovery.job')::jsonb->'run'->>'id'),true);
update public.execution_runs set claim_recoveries=3,claim_expires_at=clock_timestamp()-interval '1 second' where id=current_setting('recovery.id')::uuid;
set local role testpilot_runner;
select pg_temp.assert_true(public.claim_test_execution() is null,'recovery bounded to three unsent retries');
reset role;
select pg_temp.assert_true((select recovery_outcome='EXHAUSTED' from public.execution_runs where id=current_setting('recovery.id')::uuid),'exhausted execution explicitly terminal');
select set_config('recovery.job',pg_temp.recovery_job()::text,true);
select set_config('recovery.id',(current_setting('recovery.job')::jsonb->'run'->>'id'),true);
update public.execution_runs set cancel_requested=true,claim_expires_at=clock_timestamp()-interval '1 second' where id=current_setting('recovery.id')::uuid;
set local role testpilot_runner;
select pg_temp.assert_true(public.claim_test_execution() is null,'cancelled unsent work never reclaimed');
reset role;
select pg_temp.assert_true((select status='CANCELLED' and recovery_outcome='CANCELLED' from public.execution_runs where id=current_setting('recovery.id')::uuid),'cancelled recovery terminal');
select pg_temp.assert_true((select relrowsecurity from pg_class where oid='public.execution_recovery_events'::regclass),'recovery audit RLS enabled');
select pg_temp.assert_true(not has_table_privilege('testpilot_runner','public.execution_recovery_events','SELECT,INSERT,UPDATE,DELETE'),'runner has no direct audit authority');
select pg_temp.assert_true(not has_function_privilege('testpilot_runner','public.recover_execution_claims()','EXECUTE'),'recovery helper private');
select pg_temp.assert_true((select count(*)=5 from pg_proc p where p.pronamespace='public'::regnamespace and has_function_privilege('testpilot_runner',p.oid,'EXECUTE') and p.proname in ('claim_test_execution','record_execution_safety','finish_test_execution','execution_cancel_requested','authorize_execution_send')),'runner still exactly five RPCs');
set local role authenticated;
select set_config('request.jwt.claim.sub','14000000-0000-0000-0000-000000000002',true);
select pg_temp.assert_true((select count(*)=0 from public.execution_recovery_events),'cross-tenant audit hidden');
reset role;
select count(*) as runner_recovery_assertions from pg_temp.qa_results;
rollback;
